Document: libcryptoauth
Title: Debian libcryptoauth Manual
Author: <insert document author here>
Abstract: This manual describes what libcryptoauth is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcryptoauth/libcryptoauth.sgml.gz

Format: postscript
Files: /usr/share/doc/libcryptoauth/libcryptoauth.ps.gz

Format: text
Files: /usr/share/doc/libcryptoauth/libcryptoauth.text.gz

Format: HTML
Index: /usr/share/doc/libcryptoauth/html/index.html
Files: /usr/share/doc/libcryptoauth/html/*.html
